version: "3"

services:
  backend:
    container_name: pa_backend
    build:
      context: .
      dockerfile: ./infra/backend/Dockerfile
    volumes:
      - ./backend:/usr/src/app
    stdin_open: true
    tty: true
    env_file:
      - ./infra/env/backend-prod.env
    ports:
      - 8080:8080
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec puma -C config/puma.rb -p 8080 -b \"http://160.16.51.70\""
