openapi: 3.0.0
info:
  title: progaku-archive
  version: 1.0.0
servers:
  - url: https://localhost:3000
    description: 開発環境
tags:
  - name: メモ
    description: メモに関するAPI

paths:
  /memos:
    $ref: './paths/memo.yml'
  /memos/{memoId}:
    $ref: './paths/memoId.yml'