name: Backend CI
on: pull_request

jobs:
  rspec_and_rubocop:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: copy backend.env.template
        run: cp infra/env/backend.env.template infra/env/backend.env

      - name: Build Docker image
        run: |
          docker compose build backend
      
      - name: Create and Setup DB
        run: |
          for i in {1..10}; do
            docker compose run backend rails db:create RAILS_ENV=test && break
            echo "Waiting for MySQL to be ready..."
            sleep 5
          done


      - name: Run Rubocop
        run: docker compose run backend bundle exec rubocop
      
      - name: Run Rspec
        run: docker compose run backend bundle exec rspec
