name: Backend Test and Lint
on: pull_request

jobs:
  Rubocop:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: copy backend.env.template
        run: cp infra/env/backend.env.template infra/env/backend.env

      - name: Build Docker image
        run: docker compose build backend

      - name: Run Rubocop
        run: docker compose run backend bundle exec rubocop
