name: Deploy Swagger UI to Pages

on:
  push:
    branches:
      - main
    paths:
      - backend/doc/**
      - .github/workflows/deploy_openapi.yml
  workflow_dispatch:

permissions:
  contents: write

jobs:
  swagger-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install swagger-cli
        run: |
          npm install -g swagger-cli

      - name: Validate swagger files
        run: |
          swagger-cli validate -d ./backend/doc/openapi.yml --type yaml --format 3

  swagger-release:
    needs: swagger-validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create deploy directory
        run: |
          mkdir -p docs/swagger

      - name: Copy OpenAPI file
        run: |
          cp backend/doc/openapi.yml docs/swagger/openapi.yaml

      - name: Copy Swagger static files
        run: |
          wget https://github.com/swagger-api/swagger-ui/archive/refs/tags/v5.11.8.tar.gz
          tar -zxvf v5.11.8.tar.gz
          cp -r swagger-ui-5.11.8/dist/* docs/swagger/
          sed -i 's|https://petstore.swagger.io/v2/swagger.json|./openapi.yaml|' docs/swagger/swagger-initializer.js

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/swagger